import 'dart:math' as math;
import 'package:flame/components.dart';
import 'package:flutter/material.dart';
import '../moba_game.dart';
import 'bot_enemy.dart';
import 'turret.dart';
import 'jungle_monster.dart';
import 'minion.dart';
class HeroPlayerComponent extends PositionComponent with HasGameRef<MOBAOfflineGame>{
 double maxHp=320,hp=320,mana=100,speed=185,baseDamage=28,baseSkillDamage=75,attackCooldown=0,skillCooldown=0;bool isDead=false;Vector2 facing=Vector2(1,0);
 HeroPlayerComponent():super(position:Vector2(-2350,0),size:Vector2.all(72),anchor:Anchor.center);
 @override void update(double dt){super.update(dt);if(isDead)return;attackCooldown=math.max(0,attackCooldown-dt);skillCooldown=math.max(0,skillCooldown-dt);mana=math.min(100,mana+dt*5);final input=gameRef.joystick.relativeDelta;if(input.length2>.01){facing=input.normalized();position+=facing*speed*dt;position.x=position.x.clamp(-2850,2850).toDouble();position.y=position.y.clamp(-1650,1650).toDouble();}if(hp<maxHp)hp=math.min(maxHp,hp+dt);}
 void basicAttack(bool premium){if(isDead||attackCooldown>0)return;attackCooldown=premium?0.22:.45;dynamic target;double best=double.infinity;for(final e in gameRef.enemies){if(!e.isDead){final d=e.position.distanceTo(position);if(d<best&&d<420){best=d;target=e;}}}for(final m in gameRef.minions){if(!m.isRemoved&&!m.allied){final d=m.position.distanceTo(position);if(d<best&&d<350){best=d;target=m;}}}for(final m in gameRef.monsters){if(!m.dead){final d=m.position.distanceTo(position);if(d<best&&d<350){best=d;target=m;}}}for(final t in gameRef.turrets){if(!t.allied&&!t.destroyed){final d=t.position.distanceTo(position);if(d<best&&d<330){best=d;target=t;}}}final dir=target==null?facing:(target.position-position).normalized();facing=dir.clone();final dmg=premium?baseDamage*1.45:baseDamage;if(target is BotEnemyComponent)target.takeDamage(dmg);else if(target is MinionComponent)target.takeDamage(dmg);else if(target is JungleMonster)target.takeDamage(dmg);else if(target is TurretComponent)target.takeDamage(dmg*.75);}
 void useSkill(){if(isDead||skillCooldown>0||mana<30)return;skillCooldown=5;mana-=30;for(final e in List<BotEnemyComponent>.from(gameRef.enemies)){if(!e.isDead&&e.position.distanceTo(position)<240)e.takeDamage(baseSkillDamage);}for(final m in List<MinionComponent>.from(gameRef.minions)){if(!m.isRemoved&&!m.allied&&m.position.distanceTo(position)<240)m.takeDamage(baseSkillDamage*.8);}for(final m in List<JungleMonster>.from(gameRef.monsters)){if(!m.dead&&m.position.distanceTo(position)<240)m.takeDamage(baseSkillDamage*.8);}gameRef.flashMessage('${gameRef.selectedHero.name} • SKILL AREA!');}
 void takeDamage(double damage){if(isDead)return;hp-=damage;if(hp<=0){hp=0;isDead=true;gameRef.triggerGameOver();}}
 void reset(){isDead=false;hp=maxHp;mana=100;attackCooldown=0;skillCooldown=0;position=Vector2(-2350,0);facing=Vector2(1,0);}
 @override void render(Canvas c){final s=size.x/72,o=Offset(size.x/2,size.y/2);final armor=gameRef.selectedHero.id=='lyra'?const Color(0xff9c6bff):const Color(0xff39a9ff);c.drawOval(Rect.fromCenter(center:Offset(o.dx,o.dy+25*s),width:50*s,height:15*s),Paint()..color=Colors.black45);c.drawPath(Path()..moveTo(o.dx-19*s,o.dy-1*s)..lineTo(o.dx+19*s,o.dy-1*s)..lineTo(o.dx+14*s,o.dy+25*s)..lineTo(o.dx-14*s,o.dy+25*s)..close(),Paint()..color=const Color(0xff174f91));c.drawCircle(Offset(o.dx,o.dy-14*s),15*s,Paint()..color=armor);c.drawArc(Rect.fromCircle(center:Offset(o.dx,o.dy-14*s),radius:16*s),math.pi,math.pi,true,Paint()..color=const Color(0xff132d55));c.drawCircle(Offset(o.dx-5*s,o.dy-16*s),2.5*s,Paint()..color=Colors.white);c.drawCircle(Offset(o.dx+5*s,o.dy-16*s),2.5*s,Paint()..color=Colors.white);final d=facing.normalized();c.drawLine(Offset(o.dx+d.x*13*s,o.dy+d.y*13*s),Offset(o.dx+d.x*34*s,o.dy+d.y*34*s),Paint()..color=Colors.white..strokeWidth=5*s);c.drawRect(Rect.fromLTWH(5,1,size.x-10,6),Paint()..color=Colors.black87);c.drawRect(Rect.fromLTWH(5,1,(size.x-10)*math.max(0,hp/maxHp),6),Paint()..color=Colors.limeAccent);}
}
